# redis-ha:
#   enabled: true

controller:
  enableStatefulSet: true

server:
  autoscaling:
    enabled: true
    minReplicas: 2
  service:
    type: LoadBalancer

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
